sudo: false
dist: xenial
language: csharp
mono: none
dotnet: 3.1
solution: RegionAPI.sln
services:
    - docker
env:
    - ASPNETCORE_ENVIRONMENT=Test

before_install:
    
install: true

before_script:
    - sudo apt-get install libgdiplus
    - sleep 60

script:
    - dotnet restore RegionApiTest/RegionApiTest.csproj
    - dotnet build RegionApiTest/RegionApiTest.csproj
    - dotnet test RegionApiTest/RegionApiTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - chmod +x codecov
    - ./codecov -f "/home/travis/build/danliris/RegionAPI/RegionApiTest/coverage.info"
